/**
 * POC page (poc-bg-removal.html): validates the client-side RMBG-1.4 removal
 * + black outline pipeline against the REAL Perchance plugin outputs
 * (rpg/public/poc/sprite-a.jpeg, sprite-b.jpeg). Reuses the app modules
 * exactly as shipped (bg-removal.ts, sprite-outline.ts).
 */
import { cleanSpriteMatte } from "../scene/sprite-matte";
import { buildOutlineDataUrl } from "../scene/sprite-outline";
import {
  backgroundRemovalReady,
  preloadBackgroundRemoval,
  removeBackgroundClient,
} from "../services/bg-removal";
import spriteAUrl from "./sprite-a.jpeg";
import spriteBUrl from "./sprite-b.jpeg";

const SAMPLES = [
  { id: "sprite-a", file: spriteAUrl, label: "sample A (raw plugin output)" },
  { id: "sprite-b", file: spriteBUrl, label: "sample B (raw plugin output)" },
];

const statusEl = document.getElementById("status");
const cardsEl = document.getElementById("cards");
if (!statusEl || !cardsEl) throw new Error("poc: missing mount elements");
const status = statusEl;
const cards = cardsEl;
const runButton = document.getElementById("run") as HTMLButtonElement;

function setStatus(text: string, error = false): void {
  status.textContent = text;
  status.classList.toggle("error", error);
  status.classList.toggle("loading", !error);
}

function img(src: string, alt: string): HTMLImageElement {
  const el = document.createElement("img");
  el.src = src;
  el.alt = alt;
  return el;
}

function card(title: string, image: HTMLImageElement, meta: string): HTMLElement {
  const el = document.createElement("div");
  el.className = "card";
  const h = document.createElement("h3");
  h.textContent = title;
  const m = document.createElement("div");
  m.className = "meta";
  m.textContent = meta;
  el.append(h, image, m);
  return el;
}

async function process(sample: { id: string; file: string; label: string }): Promise<void> {
  // Same order as the app pipeline (scene/assets.ts): remove → matte → outline.
  const removed = await removeBackgroundClient(sample.file);
  const cleaned = await cleanSpriteMatte(removed);
  const outline = await buildOutlineDataUrl(cleaned, { radius: 6 });

  const row = document.createElement("div");
  row.className = "row";
  const removedEl = document.createElement("img");
  removedEl.src = cleaned;
  removedEl.alt = "removed";
  const outlineEl = document.createElement("img");
  outlineEl.src = outline;
  outlineEl.alt = "outline";
  row.append(
    card(`original — ${sample.label}`, img(sample.file, "original"), "as generated by the plugin"),
    card("removed (RMBG-1.4)", removedEl, "alpha cut out client-side"),
    card("outline (black border)", outlineEl, "dilated silhouette behind the sprite"),
  );
  cards.append(row);
}

async function run(): Promise<void> {
  runButton.disabled = true;
  cards.innerHTML = "";

  const modelStart = performance.now();
  setStatus("Loading model (first run downloads ~45 MB — cached afterwards)…");
  preloadBackgroundRemoval();
  try {
    await backgroundRemovalReady();
  } catch (error) {
    setStatus(
      `Model failed to load: ${error instanceof Error ? error.message : String(error)}`,
      true,
    );
    return;
  }
  const modelMs = Math.round(performance.now() - modelStart);

  setStatus(`Model ready in ${modelMs} ms. Processing samples…`);
  try {
    const timings: string[] = [];
    for (const sample of SAMPLES) {
      const t0 = performance.now();
      await process(sample);
      timings.push(`${sample.id}: ${Math.round(performance.now() - t0)} ms`);
    }
    setStatus(`Done — model load ${modelMs} ms · ${timings.join(" · ")}`);
  } catch (error) {
    setStatus(`Processing failed: ${error instanceof Error ? error.message : String(error)}`, true);
  } finally {
    runButton.disabled = false;
  }
}

runButton.addEventListener("click", () => void run());
void run();
